name = "linkedin-connector-backend"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
SUPABASE_URL = "https://sunfqzqxhpmvpidenqtb.supabase.co"
GROQ_API_URL = "https://api.groq.com"
LINKEDIN_CLIENT_ID = "77ippt2xqbmkx1"

[triggers]
crons = [ "*/30 * * * *" ]

